input_path: "data/01_raw/marte.jpg"
output_path: "data/03_primary/marte_processed.jpg"
rotation_angle: 90
filter_name: "FIND_EDGES"
watermark_text: "Jesus Ramos - UCV VII Ciclo - Sistemas Inteligentes"